### ISSUE TITLE
Not detecting latest chain length in disk mode

### ISSUE THREAD

**Issue by brickinedifice** [citp/BlockSci#100]
Hi: I am running the parser in disk mode. The last time (and first time) I ran the parser, it updated to a chain of 517549 blocks.  Right now the latest block file in `bitcoin_core/blocks` folder is `blk01246.dat` corresponding to chain length of 520xxx.  *When I run the parser to update, it is not detecting the latest chain length.*  I am running the following command to update. 

`sudo nohup blocksci_parser -o bitcoin_data update disk -c bitcoin_core >> log &`  

The log file states this:

`100.0% done fetching block headers`
`Starting with chain of 517549 blocks`
`Removing 0 blocks`
`Adding 0 blocks`
`Updating hash index`
`Updating address index`
`Updating index with scripts of type multisig_script`

Any thoughts on how I can move forward?

Thanks.

**Comment by yiwesi** [comment]
Did you run the parser to update on the same maschine with which you initial parsed your 517549 blocks?

**Comment by brickinedifice** [comment]
The parser is being run on the same machine. However, the initial parsing job pointed to a mounted filesystem and this new parsing job is pointing to a different one.  

Thanks.

**Comment by hkalodner** [comment]
Hmm, so the problem is resolved? I'm not sure I understand exactly what went wrong.

**Comment by brickinedifice** [comment]
Thanks. I am afraid the problem is not yet resolved. 

To clarify, when I run the blocksci parser using the command above, it finds the chain length to be 517549. However, when I run bitcoin-cli getblockcount on the same bitcoin folder, it finds blocks length of 520k+.  

Is there a debug or deeper logging mode in blocksci?

**Comment by hkalodner** [comment]
I just updated the parser to finally resolve #69 which might be the same issue here. Can you update to the latest commit on the master branch and try running the parser again?

**Comment by brickinedifice** [comment]
Thanks for trying to fix the issue. Will do.

**Comment by brickinedifice** [comment]
Thanks. In the long run do you think disk and RPC mode have equal
likelihood of being maintained or do you think the RPC mode is more likely?

**Comment by brickinedifice** [comment]
It looks like the local compile instructions don't have steps to make rocksdb among other things that was required when I first installed BlockSci.  Does using the latest commit on master mean that the indexing will start from scratch? Or will it pick up where I last left it?

Thanks. DB.

**Comment by brickinedifice** [comment]
Tried to compile. The last step (pip3) is failing for me.  Please attached log file. 
 
Am I doing something incorrectly?
[log.txt](https://github.com/citp/BlockSci/files/1977986/log.txt)

**Comment by hkalodner** [comment]
Hmm. I thought I had solved the issues related to previous installations interfering, but I guess not. I refactored a lot in this release and it's mixing new files and old files. The quick fix should be deleting `/usr/include/blocksci/` and installing BlockSci again.

**Comment by brickinedifice** [comment]
Sounds good. Will give that a shot.

**Comment by brickinedifice** [comment]
Deleting /usr/local/include/blocksci. I don’t have a /usr/include/blocksci directory.

**Comment by brickinedifice** [comment]
I am afraid it doesn't look as if it worked.  It's giving me the same message as what is at the very top of this issue. 

However, I noticed that the blocksci_parser in /usr/local/bin did not change.  Should this have changed?  

At the same time, the latest compilation process put includes in /usr/include/blocksci and not in /usr/local/include/blocksci.  Does this matter? 

Thanks.

**Comment by brickinedifice** [comment]
Some progress.  Now I am getting this error. 

`blocksci_parser: symbol lookup error: blocksci_parser: undefined symbol: _ZN8blocksci17DataConfigurationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Thoughts on possible paths forward?

**Comment by ddolgov** [comment]
Same issue (parser not updating even though blockchain is) on v0.5 installed brand-new in the beginning of June. I am not sure #69 was completely resolved yet.

**Comment by hoopyoung** [comment]
Same issue. Use BlockSci v0.5, delete `/usr/include/blocksci/` and install BlockSci again,still the problem.

diego@big:~/.bitcoin$ bitcoin-cli getblockcount
539871

diego@big:~/parsedata$ blocksci_parser -o btc update disk -c /home/diego/.bitcoin
100.0% done fetching block headers
Starting with chain of 539009 blocks
Removing 0 blocks
Adding 0 blocks
Updating hash index
Updating address index
Updating index with scripts of type multisig_script
